export const CATALOG_E = `
Docker Engine|T|d,v,i|o|Open container runtime and tooling for building and running OCI containers.|https://docs.docker.com/engine/install/|https://docs.docker.com/engine/|containers,oci,runtime,cli||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,windows|local,self-hosted
Podman|T|d,v,i|o|Daemonless container engine for OCI containers and pods.|https://podman.io/docs/installation|https://docs.podman.io/|containers,oci,pods,rootless||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local,self-hosted
Kubernetes|T|d,v,i|o|Production-grade orchestration for containerized applications.|https://kubernetes.io/docs/setup/|https://kubernetes.io/docs/home/|kubernetes,containers,orchestration,cluster||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted,cloud
k3s|T|v,i|o|Lightweight certified Kubernetes distribution for edge and homelab environments.|https://docs.k3s.io/quick-start|https://docs.k3s.io/|kubernetes,edge,homelab,lightweight||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted
Rancher|T|v,i|o|Multi-cluster Kubernetes management and operations platform.|https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade|https://ranchermanager.docs.rancher.com/|kubernetes,cluster,management,platform||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted,cloud
Portainer CE|T|v,i|o|Web interface for managing Docker, Kubernetes and edge environments.|https://docs.portainer.io/start/install-ce|https://docs.portainer.io/|containers,docker,kubernetes,management||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Helm|T|d,v|o|Package manager for installing and upgrading Kubernetes applications.|https://helm.sh/docs/intro/install/|https://helm.sh/docs/|kubernetes,packages,charts,cli||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local,cloud
Harbor|T|v,s|o|Trusted cloud-native registry for container images and OCI artifacts.|https://goharbor.io/docs/latest/install-config/|https://goharbor.io/docs/|registry,containers,oci,security||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted
Argo CD|S|d,v|o|Declarative GitOps continuous delivery for Kubernetes.|https://argo-cd.readthedocs.io/en/stable/getting_started/|https://argo-cd.readthedocs.io/|gitops,kubernetes,continuous delivery,deployment||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted,cloud
Flux CD|S|d,v|o|GitOps toolkit for continuously reconciling Kubernetes clusters.|https://fluxcd.io/flux/installation/|https://fluxcd.io/flux/|gitops,kubernetes,continuous delivery,reconciliation||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted,cloud
Jenkins|S|d,v|o|Extensible automation server for CI, CD and operational workflows.|https://www.jenkins.io/doc/book/installing/|https://www.jenkins.io/doc/|ci,cd,automation,pipelines||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|self-hosted
Woodpecker CI|S|d,v|o|Community-driven CI system with container-based pipelines.|https://woodpecker-ci.org/docs/administration/getting-started|https://woodpecker-ci.org/docs/|ci,pipelines,containers,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Tekton|S|d,v|o|Kubernetes-native framework for building CI/CD systems.|https://tekton.dev/docs/installation/|https://tekton.dev/docs/|ci,cd,kubernetes,pipelines||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted,cloud
Dagger|S|d,v|o|Programmable CI/CD engine that runs pipelines in containers.|https://docs.dagger.io/install|https://docs.dagger.io/|ci,cd,containers,developer tools||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local,cloud
act|S|d,v|o|Run GitHub Actions workflows locally in Docker containers.|https://nektosact.com/installation/index.html|https://nektosact.com/|github actions,ci,local,docker||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local
OpenTofu|U|v,i|o|Open-source infrastructure-as-code engine compatible with Terraform workflows.|https://opentofu.org/docs/intro/install/|https://opentofu.org/docs/|iac,infrastructure,terraform,cli||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local,cloud
Pulumi|U|d,v|o|Infrastructure as code using TypeScript, Python, Go, .NET, Java and YAML.|https://www.pulumi.com/docs/iac/download-install/|https://www.pulumi.com/docs/|iac,infrastructure,cloud,automation||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local,cloud
Ansible|U|v,i|o|Agentless configuration management, provisioning and application deployment.|https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html|https://docs.ansible.com/|configuration management,automation,ssh,provisioning||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos|local,self-hosted
Salt Project|U|v,i|o|Event-driven infrastructure automation and configuration management.|https://docs.saltproject.io/salt/install-guide/en/latest/|https://docs.saltproject.io/|configuration management,automation,orchestration,remote||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|self-hosted
Packer|U|v,i|f|Machine-image automation for repeatable cloud and VM infrastructure.|https://developer.hashicorp.com/packer/install|https://developer.hashicorp.com/packer/docs|images,automation,infrastructure,vm||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local,cloud
Vagrant|U|d,v,i|f|Declarative local development environments using virtual machines or containers.|https://developer.hashicorp.com/vagrant/install|https://developer.hashicorp.com/vagrant/docs|development environment,vm,automation,local||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local
Backstage|S|d,v|o|Open platform for building internal developer portals and service catalogs.|https://backstage.io/docs/getting-started/|https://backstage.io/docs/|developer portal,service catalog,platform engineering,plugins||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos|self-hosted
Atlantis|U|v|o|Terraform and OpenTofu pull-request automation for teams.|https://www.runatlantis.io/docs/deployment.html|https://www.runatlantis.io/docs/|terraform,opentofu,pull requests,automation||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted,cloud
LocalStack|V|d,v|o|Local cloud emulator for developing and testing AWS applications offline.|https://docs.localstack.cloud/getting-started/installation/|https://docs.localstack.cloud/|aws,cloud,emulator,testing||2026-07-13|https://github.com/wmariuss/awesome-devops|linux,macos,windows|local,self-hosted
GLPI|V|i,o|o|IT asset management, service desk and CMDB platform.|https://glpi-project.org/downloads/|https://help.glpi-project.org/|itam,asset management,helpdesk,cmdb||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
Snipe-IT|V|i,o|o|Web-based IT asset and software-license management.|https://snipe-it.readme.io/docs/installation|https://snipe-it.readme.io/docs|itam,assets,licenses,inventory||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
NetBox|V|i,v|o|Infrastructure resource modeling for networks, devices, IPAM and data centers.|https://netboxlabs.com/docs/netbox/installation/|https://netboxlabs.com/docs/netbox/|ipam,dcim,network,inventory||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
Zabbix|M|i,v|o|Infrastructure, network and application monitoring platform.|https://www.zabbix.com/download|https://www.zabbix.com/documentation/current/en/manual|monitoring,metrics,network,alerts||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
Icinga|M|i,v|o|Monitoring system for hosts, services, networks and cloud resources.|https://icinga.com/docs/icinga-2/latest/doc/02-installation/|https://icinga.com/docs/|monitoring,alerts,infrastructure,network||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
Uptime Kuma|M|i,v|o|Self-hosted uptime monitor with notifications and status pages.|https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install|https://github.com/louislam/uptime-kuma/wiki|uptime,monitoring,status page,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Cockpit|V|i|o|Browser-based administration interface for Linux servers.|https://cockpit-project.org/running.html|https://cockpit-project.org/guide/latest/|linux,server,administration,web ui||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
Webmin|V|i|o|Web-based system administration interface for Unix-like servers.|https://webmin.com/download/|https://webmin.com/docs/|linux,server,administration,control panel||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
Proxmox VE|V|i,v|o|Virtualization platform for KVM virtual machines and LXC containers.|https://www.proxmox.com/en/downloads/proxmox-virtual-environment|https://pve.proxmox.com/pve-docs/|virtualization,kvm,lxc,cluster||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
MeshCentral|X|i,s|o|Web-based remote device management and support platform.|https://meshcentral.com/info/downloads.html|https://ylianst.github.io/MeshCentral/|remote access,device management,support,endpoint||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|self-hosted
RustDesk|X|i,p|o|Open-source remote desktop and remote support software.|https://rustdesk.com/docs/en/client/|https://rustdesk.com/docs/|remote desktop,support,screen sharing,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows,mobile|local,self-hosted
Apache Guacamole|X|i|o|Clientless remote desktop gateway supporting RDP, VNC and SSH.|https://guacamole.apache.org/doc/gug/installing-guacamole.html|https://guacamole.apache.org/doc/gug/|remote desktop,rdp,vnc,ssh||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
osTicket|AB|i,o|o|Open-source help desk and customer support ticketing system.|https://docs.osticket.com/en/latest/Getting%20Started/Installation.html|https://docs.osticket.com/|helpdesk,ticketing,support,service desk||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
FreeScout|AB|i,o|o|Lightweight shared mailbox and help desk application.|https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide|https://github.com/freescout-helpdesk/freescout/wiki|helpdesk,shared inbox,email,support||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Zammad|AB|i,o|o|Web-based help desk and customer support platform.|https://docs.zammad.org/en/latest/install/index.html|https://docs.zammad.org/|helpdesk,ticketing,customer support,service desk||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Proxmox Backup Server|W|i,v|o|Enterprise backup for virtual machines, containers and physical hosts.|https://www.proxmox.com/en/downloads/proxmox-backup-server|https://pbs.proxmox.com/docs/|backup,virtualization,deduplication,recovery||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux|self-hosted
BorgBackup|W|i,v|o|Deduplicating encrypted backup tool with compression and remote repositories.|https://borgbackup.readthedocs.io/en/stable/installation.html|https://borgbackup.readthedocs.io/|backup,encryption,deduplication,cli||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos|local,self-hosted
Restic|W|i,v|o|Fast, verifiable and encrypted backup program for many storage backends.|https://restic.readthedocs.io/en/stable/020_installation.html|https://restic.readthedocs.io/|backup,encryption,cloud storage,cli||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|local,self-hosted,cloud
Kopia|W|i,v|o|Encrypted deduplicated backups with CLI, server and desktop interfaces.|https://kopia.io/docs/installation/|https://kopia.io/docs/|backup,encryption,deduplication,desktop||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|local,self-hosted,cloud
Duplicati|W|i,p|o|Encrypted incremental backups to local and cloud storage providers.|https://docs.duplicati.com/getting-started/installation|https://docs.duplicati.com/|backup,encryption,cloud storage,desktop||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|local,self-hosted,cloud
rclone|W|i,v|o|Command-line sync and transfer tool for cloud and object storage providers.|https://rclone.org/install/|https://rclone.org/docs/|backup,sync,cloud storage,cli||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|local,cloud
UrBackup|W|i|o|Client-server network backup for Windows, Linux and macOS devices.|https://www.urbackup.org/download.html|https://www.urbackup.org/administration_manual.html|backup,endpoint,network,recovery||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|self-hosted
Syncthing|Y|i,p|o|Continuous peer-to-peer file synchronization across devices.|https://syncthing.net/downloads/|https://docs.syncthing.net/|file sync,p2p,privacy,devices||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux,macos,windows,mobile|local,self-hosted
WireGuard|X|i,s,v|o|Modern high-performance VPN protocol and networking tunnel.|https://www.wireguard.com/install/|https://www.wireguard.com/quickstart/|vpn,network,tunnel,security||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows,mobile|local,self-hosted
Headscale|X|i,s,v|o|Self-hosted coordination server compatible with Tailscale clients.|https://headscale.net/stable/setup/install/official/|https://headscale.net/stable/|vpn,wireguard,zero trust,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
NetBird|X|i,s,v|o|WireGuard-based zero-trust networking with optional self-hosting.|https://docs.netbird.io/how-to/getting-started|https://docs.netbird.io/|vpn,wireguard,zero trust,network||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows,mobile|self-hosted,cloud
Pi-hole|X|i,p|o|Network-wide DNS sinkhole for blocking ads and unwanted domains.|https://docs.pi-hole.net/main/basic-install/|https://docs.pi-hole.net/|dns,privacy,ad blocking,homelab||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
AdGuard Home|X|i,p|o|Network-wide DNS server with ad blocking and parental controls.|https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started|https://github.com/AdguardTeam/AdGuardHome/wiki|dns,privacy,ad blocking,parental controls||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|self-hosted
OpenVPN Community|X|i,s|o|Open-source VPN server and client software using TLS.|https://openvpn.net/community-downloads/|https://openvpn.net/community-resources/|vpn,network,tls,remote access||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|self-hosted
Nmap|X|i,s|o|Network discovery, inventory and security auditing toolkit.|https://nmap.org/download.html|https://nmap.org/book/man.html|network,discovery,security,audit||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|local
Wireshark|X|i,s|o|Network protocol analyzer for troubleshooting and inspection.|https://www.wireshark.org/download.html|https://www.wireshark.org/docs/|network,packets,troubleshooting,security||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|local
Joplin|AA|p|o|Markdown note-taking and to-do application with end-to-end encrypted sync.|https://joplinapp.org/help/install/|https://joplinapp.org/help/|notes,markdown,tasks,sync||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux,macos,windows,mobile|local,cloud
Logseq|AA|p|o|Privacy-first knowledge base using local Markdown and Org-mode files.|https://logseq.com/downloads|https://docs.logseq.com/|notes,knowledge,markdown,local-first||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux,macos,windows,mobile|local
Obsidian|AA|p|f|Local-first knowledge base and note-taking application built around Markdown files.|https://obsidian.md/download|https://help.obsidian.md/|notes,knowledge,markdown,local-first||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux,macos,windows,mobile|local
Standard Notes|AA|p|o|Encrypted notes application with open-source clients and self-hosting options.|https://standardnotes.com/download|https://standardnotes.com/help|notes,encryption,privacy,self-host||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux,macos,windows,mobile|local,self-hosted,cloud
AppFlowy|AA|p,o|o|Open-source workspace for notes, wikis, projects and databases.|https://appflowy.com/download|https://docs.appflowy.io/|notes,wiki,projects,database||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows,mobile|local,self-hosted,cloud
TriliumNext Notes|AA|p|o|Hierarchical note-taking and personal knowledge-base application.|https://github.com/TriliumNext/Trilium/wiki/Setup|https://github.com/TriliumNext/Trilium/wiki|notes,knowledge,hierarchy,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|local,self-hosted
Vikunja|Z|p,o|o|Open-source task and project management with lists, kanban and CalDAV.|https://vikunja.io/docs/installing|https://vikunja.io/docs/|tasks,projects,kanban,caldav||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
OpenProject|Z|p,o|o|Project management for classic, agile and hybrid teams.|https://www.openproject.org/docs/installation-and-operations/installation/|https://www.openproject.org/docs/|projects,agile,kanban,planning||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux|self-hosted,cloud
Plane|Z|p,o|o|Open-source project management for issues, cycles and product roadmaps.|https://developers.plane.so/self-hosting/methods/docker-compose|https://developers.plane.so/|projects,issues,roadmap,agile||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted,cloud
Taiga|Z|p,o|o|Agile project management for Scrum and Kanban teams.|https://docs.taiga.io/setup-production.html|https://docs.taiga.io/|projects,scrum,kanban,agile||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Wekan|Z|p,o|o|Open-source collaborative Kanban board.|https://wekan.github.io/install/|https://wekan.github.io/|kanban,tasks,collaboration,boards||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Kanboard|Z|p,o|o|Minimal open-source Kanban project management software.|https://docs.kanboard.org/v1/admin/installation/|https://docs.kanboard.org/|kanban,tasks,projects,minimal||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Super Productivity|Z|p|o|Cross-platform task manager with time tracking and integrations.|https://super-productivity.com/|https://github.com/johannesjo/super-productivity/blob/master/docs/README.md|tasks,time tracking,productivity,offline||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux,macos,windows,mobile|local
Cal.com|Y|p,o|o|Open-source scheduling infrastructure and booking pages.|https://cal.com/docs/self-hosting/installation|https://cal.com/docs|scheduling,calendar,booking,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted,cloud
Nextcloud|Y|p,i,o|o|Self-hosted file sync, collaboration, calendar and office platform.|https://docs.nextcloud.com/server/latest/admin_manual/installation/|https://docs.nextcloud.com/|files,collaboration,calendar,office||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux|self-hosted
Seafile|Y|p,i,o|o|File synchronization and sharing platform with desktop and mobile clients.|https://manual.seafile.com/latest/setup_binary/|https://manual.seafile.com/|file sync,sharing,collaboration,self-host||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux,macos,windows,mobile|self-hosted
CryptPad|Y|p,o|o|Privacy-focused collaborative office suite with end-to-end encryption.|https://docs.cryptpad.org/en/admin_guide/installation.html|https://docs.cryptpad.org/|office,collaboration,encryption,documents||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|web|self-hosted,cloud
ONLYOFFICE Community|Y|p,o|o|Self-hosted collaborative editors for documents, spreadsheets and presentations.|https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx|https://api.onlyoffice.com/docs/docs-api/get-started/|office,documents,spreadsheets,collaboration||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
LibreOffice|Y|p|o|Open-source desktop suite for documents, spreadsheets and presentations.|https://www.libreoffice.org/download/download-libreoffice/|https://documentation.libreoffice.org/|office,documents,spreadsheets,presentations||2026-07-13|https://github.com/jyguyomarch/awesome-productivity|linux,macos,windows|local
Stirling-PDF|Y|p,o|o|Self-hosted web toolkit for manipulating and converting PDF files.|https://docs.stirlingpdf.com/Installation/How%20to%20install/|https://docs.stirlingpdf.com/|pdf,documents,conversion,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Paperless-ngx|AA|p,o|o|Document management system that indexes and archives scanned documents.|https://docs.paperless-ngx.com/setup/|https://docs.paperless-ngx.com/|documents,ocr,archive,search||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
BookStack|AA|p,o|o|Simple self-hosted platform for organizing documentation into books and pages.|https://www.bookstackapp.com/docs/admin/installation/|https://www.bookstackapp.com/docs/|wiki,documentation,knowledge,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Wiki.js|AA|p,o|o|Modern extensible wiki platform with multiple authentication and storage options.|https://docs.requarks.io/install|https://docs.requarks.io/|wiki,documentation,knowledge,collaboration||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Memos|AA|p|o|Lightweight self-hosted memo and note-taking service.|https://www.usememos.com/docs/install|https://www.usememos.com/docs|notes,memos,markdown,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Linkwarden|AA|p,o|o|Collaborative bookmark manager with archiving and collections.|https://docs.linkwarden.app/self-hosting/installation|https://docs.linkwarden.app/|bookmarks,archive,knowledge,collaboration||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted,cloud
Mattermost|Y|p,o,i|o|Open-source team messaging and collaboration platform.|https://docs.mattermost.com/deployment-guide/server/deploy-containers.html|https://docs.mattermost.com/|chat,collaboration,team messaging,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows,mobile|self-hosted
Rocket.Chat|Y|p,o,i|o|Team communication platform with channels, messaging and integrations.|https://docs.rocket.chat/docs/deploy-with-docker-docker-compose|https://docs.rocket.chat/|chat,collaboration,team messaging,integrations||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows,mobile|self-hosted,cloud
Zulip|Y|p,o|o|Threaded team chat organized by streams and topics.|https://zulip.readthedocs.io/en/latest/production/install.html|https://zulip.readthedocs.io/|chat,collaboration,threads,team messaging||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows,mobile|self-hosted,cloud
Jitsi Meet|Y|p,o|o|Open-source video conferencing with browser and mobile clients.|https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart|https://jitsi.github.io/handbook/|video conferencing,meetings,collaboration,webrtc||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|web,mobile|self-hosted,cloud
Element|Y|p,o|o|Open-source Matrix client for secure messaging and collaboration.|https://element.io/download|https://docs.element.io/|chat,matrix,encryption,collaboration||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows,mobile|local,cloud
ERPNext|AB|o,p|o|Open-source ERP covering accounting, CRM, inventory, HR and operations.|https://docs.frappe.io/framework/user/en/installation|https://docs.erpnext.com/|erp,accounting,crm,inventory||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted,cloud
Odoo Community|AB|o,p|o|Community edition of the modular ERP and business application suite.|https://www.odoo.com/documentation/19.0/administration/on_premise/source.html|https://www.odoo.com/documentation/|erp,crm,accounting,operations||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Dolibarr|AB|o,p|o|ERP and CRM suite for small businesses, associations and freelancers.|https://wiki.dolibarr.org/index.php/Installation|https://wiki.dolibarr.org/|erp,crm,invoicing,inventory||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,windows|self-hosted
Twenty CRM|AB|o,p|o|Modern open-source CRM for managing companies, contacts and opportunities.|https://docs.twenty.com/developers/self-hosting|https://docs.twenty.com/|crm,sales,contacts,open source||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted,cloud
EspoCRM|AB|o,p|o|Open-source CRM for sales, marketing and customer support workflows.|https://docs.espocrm.com/administration/installation/|https://docs.espocrm.com/|crm,sales,marketing,customer support||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Mautic|AB|o,p|o|Open-source marketing automation for campaigns, contacts and email journeys.|https://docs.mautic.org/en/5.x/getting_started/how_to_install_mautic.html|https://docs.mautic.org/|marketing,automation,email,campaigns||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Invoice Ninja|AB|o,p|o|Invoicing, payments, expenses and time tracking for freelancers and teams.|https://invoiceninja.github.io/docs/self-host-installation/|https://invoiceninja.github.io/|invoicing,payments,expenses,time tracking||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,mobile|self-hosted,cloud
Kimai|AB|o,p|o|Open-source time tracking for teams, projects and billable work.|https://www.kimai.org/documentation/installation.html|https://www.kimai.org/documentation/|time tracking,timesheets,projects,invoicing||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Firefly III|AB|p|o|Personal finance manager for budgets, accounts and transactions.|https://docs.firefly-iii.org/how-to/firefly-iii/installation/|https://docs.firefly-iii.org/|finance,budgeting,transactions,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Metabase|AC|a,o|o|Business intelligence and dashboards with a visual query builder.|https://www.metabase.com/docs/latest/installation-and-operation/installing-metabase|https://www.metabase.com/docs/latest/|bi,dashboards,analytics,sql||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|self-hosted,cloud
Apache Superset|AC|a,o|o|Enterprise data exploration and visualization platform.|https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/|https://superset.apache.org/docs/|bi,dashboards,analytics,visualization||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Redash|AC|a,o|o|SQL query editor, dashboards and data-source visualization.|https://redash.io/help/open-source/setup/|https://redash.io/help/|bi,dashboards,sql,analytics||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
 dbt Core|AC|a,d|o|Command-line transformation workflow for analytics engineering.|https://docs.getdbt.com/docs/core/installation-overview|https://docs.getdbt.com/docs/core|analytics engineering,etl,sql,transformations||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|local,cloud
Airbyte|AC|a,d|f|Data integration platform for moving data between APIs, databases and warehouses.|https://docs.airbyte.com/using-airbyte/getting-started/oss-quickstart|https://docs.airbyte.com/|etl,data integration,connectors,warehouse||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted,cloud
Meltano|AC|a,d|o|Open-source data integration and orchestration platform built around ELT pipelines.|https://docs.meltano.com/getting-started/installation|https://docs.meltano.com/|etl,elt,data integration,orchestration||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|local,self-hosted
Dagster|AC|a,d|o|Data orchestrator for developing, testing and operating data assets.|https://docs.dagster.io/getting-started/installation|https://docs.dagster.io/|data orchestration,pipelines,assets,python||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|local,self-hosted,cloud
Apache Airflow|AC|a,d|o|Workflow orchestration platform for scheduled data pipelines.|https://airflow.apache.org/docs/apache-airflow/stable/installation/index.html|https://airflow.apache.org/docs/|data orchestration,pipelines,scheduler,python||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted,cloud
DuckDB|AC|a,d|o|In-process analytical SQL database for local and embedded workloads.|https://duckdb.org/docs/stable/installation/|https://duckdb.org/docs/stable/|analytics,sql,olap,embedded||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|local,embedded
DBeaver Community|AC|a,d,i|o|Cross-platform database client for SQL and NoSQL data sources.|https://dbeaver.io/download/|https://dbeaver.com/docs/dbeaver/|database,sql,client,administration||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|local
Great Expectations|AC|a,d|o|Data quality validation, documentation and testing framework.|https://docs.greatexpectations.io/docs/core/introduction/try_gx/|https://docs.greatexpectations.io/|data quality,testing,validation,documentation||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|local,cloud
Evidence|AC|a,o|o|Build data products and reports using SQL and Markdown.|https://docs.evidence.dev/install-evidence/|https://docs.evidence.dev/|bi,reports,sql,markdown||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux,macos,windows|local,self-hosted
Lightdash|AC|a,o|o|Open-source BI platform designed for dbt projects.|https://docs.lightdash.com/self-host/customize-deployment/|https://docs.lightdash.com/|bi,dbt,dashboards,analytics||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted,cloud
Coolify|AD|v,i|o|Self-hosted application platform for deploying apps, databases and services.|https://coolify.io/docs/get-started/installation|https://coolify.io/docs/|paas,deploy,self-host,containers||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Dokku|AD|v,i|o|Docker-powered mini-PaaS with git-push deployments.|https://dokku.com/docs/getting-started/installation/|https://dokku.com/docs/|paas,deploy,docker,git||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted
CapRover|AD|v,i|o|Self-hosted PaaS for one-click apps and Docker deployments.|https://caprover.com/docs/get-started.html|https://caprover.com/docs/|paas,deploy,docker,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
CasaOS|AD|i,p|o|Personal cloud interface and app store for home servers.|https://wiki.casaos.io/en/get-started|https://wiki.casaos.io/|homelab,personal cloud,apps,server||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
YunoHost|AD|i,p|o|Server operating system for simplified self-hosting and app management.|https://yunohost.org/en/install|https://yunohost.org/en/docs|self-host,server,apps,administration||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Homarr|AD|i,p|o|Customizable dashboard for homelab services and integrations.|https://homarr.dev/docs/getting-started/installation/|https://homarr.dev/docs/|dashboard,homelab,services,self-host||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Homepage|AD|i,p|o|Highly customizable application dashboard with service integrations.|https://gethomepage.dev/installation/|https://gethomepage.dev/|dashboard,homelab,services,widgets||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Dashy|AD|i,p|o|Feature-rich personal dashboard for links, services and status checks.|https://dashy.to/docs/deployment/|https://dashy.to/docs/|dashboard,homelab,links,status||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Nginx Proxy Manager|AD|i,v|o|Web interface for reverse proxy hosts, TLS certificates and access lists.|https://nginxproxymanager.com/setup/|https://nginxproxymanager.com/guide/|reverse proxy,tls,network,homelab||2026-07-13|https://github.com/awesome-selfhosted/awesome-selfhosted|linux|self-hosted
Caddy|AD|i,v,d|o|Automatic HTTPS web server and reverse proxy with a simple configuration model.|https://caddyserver.com/docs/install|https://caddyserver.com/docs/|web server,reverse proxy,tls,automatic https||2026-07-13|https://github.com/awesome-foss/awesome-sysadmin|linux,macos,windows|local,self-hosted
Traefik Proxy|AD|i,v|o|Cloud-native application proxy and ingress controller with service discovery.|https://doc.traefik.io/traefik/getting-started/install-traefik/|https://doc.traefik.io/traefik/|reverse proxy,ingress,kubernetes,service discovery||2026-07-13|https://github.com/wmariuss/awesome-devops|linux|self-hosted,cloud
`
