export type TesterDefinition = {
  label: string
  placeholder: string
  envNames: string[]
  note?: string
}

const key = (envNames: string[], placeholder = 'Paste API key or token', note?: string): TesterDefinition => ({
  label: 'API key or token', placeholder, envNames, note,
})

export const TESTER_DEFINITIONS: Record<string, TesterDefinition> = {
  vercel: key(['VERCEL_TOKEN']),
  netlify: key(['NETLIFY_AUTH_TOKEN', 'NETLIFY_TOKEN']),
  cloudflare: key(['CLOUDFLARE_API_TOKEN', 'CF_API_TOKEN']),
  github: key(['GITHUB_TOKEN', 'GH_TOKEN'], 'github_pat_… or ghp_…'),
  gitlab: key(['GITLAB_TOKEN', 'GITLAB_API_TOKEN'], 'glpat-…'),
  render: key(['RENDER_API_KEY']),
  neon: key(['NEON_API_KEY']),
  clerk: key(['CLERK_SECRET_KEY'], 'sk_test_…'),
  workos: key(['WORKOS_API_KEY'], 'sk_test_…'),
  gemini: key(['GOOGLE_GENERATIVE_AI_API_KEY', 'GEMINI_API_KEY', 'GOOGLE_API_KEY']),
  groq: key(['GROQ_API_KEY'], 'gsk_…'),
  openrouter: key(['OPENROUTER_API_KEY'], 'sk-or-…'),
  huggingface: key(['HUGGINGFACE_API_KEY', 'HF_TOKEN'], 'hf_…'),
  mistral: key(['MISTRAL_API_KEY']),
  cohere: key(['COHERE_API_KEY']),
  replicate: key(['REPLICATE_API_TOKEN'], 'r8_…'),
  together: key(['TOGETHER_API_KEY']),
  elevenlabs: key(['ELEVENLABS_API_KEY', 'XI_API_KEY']),
  deepgram: key(['DEEPGRAM_API_KEY']),
  stability: key(['STABILITY_API_KEY']),
  fireworks: key(['FIREWORKS_API_KEY']),
  cerebras: key(['CEREBRAS_API_KEY']),
  sambanova: key(['SAMBANOVA_API_KEY']),
  assemblyai: key(['ASSEMBLYAI_API_KEY']),
  pinecone: key(['PINECONE_API_KEY']),
  resend: key(['RESEND_API_KEY'], 're_…'),
  brevo: key(['BREVO_API_KEY', 'SENDINBLUE_API_KEY']),
  postmark: key(['POSTMARK_SERVER_TOKEN']),
  slack: key(['SLACK_BOT_TOKEN', 'SLACK_TOKEN'], 'xoxb-…'),
  discord: key(['DISCORD_BOT_TOKEN']),
  telegram: key(['TELEGRAM_BOT_TOKEN'], '123456:ABC…'),
  sentry: key(['SENTRY_AUTH_TOKEN'], 'sntrys_…'),
  axiom: key(['AXIOM_TOKEN']),
  linear: key(['LINEAR_API_KEY']),
  notion: key(['NOTION_TOKEN', 'NOTION_API_KEY'], 'secret_… or ntn_…'),
  airtable: key(['AIRTABLE_TOKEN', 'AIRTABLE_API_KEY'], 'pat…'),
  figma: key(['FIGMA_ACCESS_TOKEN', 'FIGMA_TOKEN'], 'figd_…'),
  canva: key(['CANVA_ACCESS_TOKEN']),
  unsplash: key(['UNSPLASH_ACCESS_KEY']),
  pexels: key(['PEXELS_API_KEY']),
  pixabay: key(['PIXABAY_API_KEY']),
  giphy: key(['GIPHY_API_KEY']),
  removebg: key(['REMOVE_BG_API_KEY']),
  freesound: key(['FREESOUND_API_KEY']),
  mapbox: key(['NEXT_PUBLIC_MAPBOX_TOKEN', 'MAPBOX_TOKEN'], 'pk.…'),
  maptiler: key(['MAPTILER_API_KEY']),
  geoapify: key(['GEOAPIFY_API_KEY']),
  here: key(['HERE_API_KEY']),
  opencage: key(['OPENCAGE_API_KEY']),
  locationiq: key(['LOCATIONIQ_TOKEN']),
  ipinfo: key(['IPINFO_TOKEN']),
  weatherapi: key(['WEATHERAPI_KEY']),
  openweather: key(['OPENWEATHER_API_KEY']),
  tmdb: key(['TMDB_READ_ACCESS_TOKEN'], 'eyJ…'),
  nasa: key(['NASA_API_KEY']),
  coingecko: key(['COINGECKO_API_KEY']),
  alphavantage: key(['ALPHA_VANTAGE_API_KEY']),
  exchangerate: key(['EXCHANGE_RATE_API_KEY']),
  newsapi: key(['NEWS_API_KEY']),
  abstractapi: key(['ABSTRACT_API_KEY']),
  stripe: key(['STRIPE_SECRET_KEY'], 'sk_test_…'),
  lemonsqueezy: key(['LEMONSQUEEZY_API_KEY']),
  virustotal: key(['VIRUSTOTAL_API_KEY']),
  abuseipdb: key(['ABUSEIPDB_API_KEY']),
  ipqualityscore: key(['IPQUALITYSCORE_API_KEY']),
  storyblok: key(['STORYBLOK_TOKEN']),
  datocms: key(['DATOCMS_API_TOKEN']),
  qstash: key(['QSTASH_TOKEN']),
  pipedream: key(['PIPEDREAM_API_KEY']),
  typeform: key(['TYPEFORM_TOKEN']),
  jotform: key(['JOTFORM_API_KEY']),
  formspree: key(['FORMSPREE_TOKEN']),
}
